simulation:
  t_sim: 5000
  tau: 0.05
  n_realizations: 1
  seed: 1
  init_sim_index: 1

traffic:
  min_arrival_rate: 0.4
  max_arrival_rate: 0.8
  arrival_rate_refresh_rate: 100

network:
  N_nodes: 4
  N_users: 3
  links:                # (i, j, pathloss_linear)
    - [0, 3, 1.0e-9]
    - [1, 3, 1.0e-9]
    - [2, 3, 1.0e-9]
  transmission_constraints: 1
  computational_constraints: 3
  Bw: 2.0e7
  pmax: 3.5
  N0: 3.98e-21
  user_indexes: [0,1,2,3]

task:
  data_unit_bits: 32
  image_size: 196608        # 3*256*256

optimizer:
  V: 10.0
  eta: 0.0

reliability:
  alpha: 0.12
  fnr_step_sizes: 0.5
  fnr_virtual_queues_init: 0.5
  window_length: 1
  gamma: 0.5

models:
  device: cuda
  encoder_weights: imagenet
  encoder_map:
    "0": timm-mobilenetv3_small_minimal_100
    "2": resnet18
    "3": resnet50
  encoder_pfr_predictor_map:
    "0": timm-mobilenetv3_small_minimal_100
    "2": mobileone_s0
    "3": mobileone_s0
  depth_mapping: [0, 1, 2, 3]
  models_association:
    "0": 0
    "1": 0
    "2": 0
    "3": 3
  model_list: ["D0", "D0", "D0", "D3"]

paths:
  theta_lut: utils/LUTs/theta_lut.npy
  segmentation_ckpt_tpl: utils/learning_models/D{d}/segmentation_network
  predictor_ckpt_tpl: utils/precision_predictors/D{d}/precision_predictor
  data_output_dir: ./simulation_results

threshold:
  fixed_index: null     # es. 4 se vuoi fissare, altrimenti null
